template = "https://github.com/giellalt/template-lang-und"
rev_id = 340
template_sha = "1186578fa79468b8b3349a52ce4880edc3ce8803"

[replacements]
__GLOTTOLOG_ID__ = "chuk1273"
__REPO__ = "lang-ckt"
__UND2C__ = "ckt"
__UNDEFINED__ = "Chukot"
__UND__ = "ckt"
